### ISSUE TITLE
Missing Code

### ISSUE THREAD

**Issue by G-Rilla** [CubeSpawn/MTC_Octoprint#1]
There doesn't seem to be the files required for the MTConnect adapter. All I can see is some python code the requests from the Octoprint API.

**Comment by CubeSpawn** [comment]
Hey! G-Rilla I used the default code from : https://github.com/mtconnect/cppagent and had to compile it on the PI.
The intent was to extract data from the API, write it to the adapter so the agent could publish it and thereby enable at least the write leg of the MTConnect Agent/Adapter pair for Octoprint
However, Its been a long while since I worked on this.

TBH this never worked, mainly due to the difficulty of getting data out of Octoprint. I had intended to pursue using the Logging plugin to write out a custom log, then parsing that file for the data, with some time stamping, then write that to the agent via the adapter, and while this seemed like a plausible possibility, it was totally asyncronous, so valid for reporting, but too laggy for a control loop
Then, priorities changed and things went in a different direction. so it never happened... ;-)
